CREATE TABLE `java_rule` (
	`id` INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`target` VARCHAR ( 64 ) DEFAULT NULL COMMENT ' 目标，一般指哪个系统',
	`file_name` VARCHAR ( 128 ) DEFAULT NULL COMMENT ' 文件名',
	`full_class_name` VARCHAR ( 128 ) DEFAULT NULL COMMENT '全类名',
	`simple_class_name` VARCHAR ( 256 ) DEFAULT NULL COMMENT '类名',
	`src_code` VARCHAR ( 2048 ) DEFAULT NULL COMMENT '源码',
	`byte_content` blob DEFAULT NULL	COMMENT '编译后字节码',
	`group_name` VARCHAR ( 128 ) DEFAULT NULL COMMENT '组别名称，一般指哪一系列规则',
	`name` VARCHAR ( 500 ) DEFAULT NULL COMMENT '规则名称',
	`status` INT ( 4 ) NOT NULL DEFAULT '0' COMMENT '状态，1有效 0无效',
	`sort` INT ( 11 ) DEFAULT NULL COMMENT '排序',
	`del_status` TINYINT ( 4 ) NOT NULL DEFAULT '0' COMMENT '删除标识',
	`remark` VARCHAR ( 512 ) DEFAULT NULL COMMENT '备注',
	`creator_user_name` VARCHAR ( 64 ) NOT NULL COMMENT '创建人erp',
	`created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modified_user_name` VARCHAR ( 64 ) NOT NULL COMMENT '修改人erp',
	`modified_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`version` INT ( 11 ) NOT NULL DEFAULT '0' COMMENT '版本号',
PRIMARY KEY ( `id` )
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT = 'java规则记录表';